### ISSUE TITLE
v2ray-plugin

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-shadowsocks-rust#5]
Hi
Would try openwrt-v2ray-plugin on your openwrt-dnsmasq-extra too.
Dose openwrt-v2ray-plugin + luci-app-shadowsocks-rust + openwrt-shadowsocks-rust +openwrt-dnsmasq-extra work  for building?

Thank you

**Comment by honwen** [comment]
it's all Compatible

**Comment by jack338c** [comment]
thank you 🥂
